on:
  push:
    branches:
      - deploy-docs-to-github-pages

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-doxygen-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ssciwr/doxygen-install@v2
        with:
          version: 1.16.1
      - run: |
          wget https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/14.1.5/ubuntu_24.04_graphviz-14.1.5-cmake.deb
          sudo apt install -y ./ubuntu_24.04_graphviz-14.1.5-cmake.deb
          rm ubuntu_24.04_graphviz-14.1.5-cmake.deb
      - run: doxygen
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: ./doc/html
      - uses: actions/deploy-pages@v5
